In [81]:
import numpy as np
import pandas as pd
import csv
from nltk import ngrams
from sklearn.metrics import jaccard_score
import glob

In [51]:
def jaccard_similarity(list1, list2):
    intersection = len(list(set(list1).intersection(list2)))
    union = (len(list1) + len(list2)) - intersection
    return float(intersection) / union

In [96]:
corpus = []

file_list = glob.glob("data/corpus-20090418/*.txt")
for file_path in file_list:
    with open(file_path, encoding="utf8", errors='ignore') as file_input:
        doc = file_input.read()
        doc = doc.replace('\n', ' ')
        doc = doc.replace('  ', ' ')
        corpus.append(doc)

In [100]:
nrow = len(corpus)
k = 3
list_kShingles = []
list_hashed = []
for i in range(nrow):
    tokens = corpus[i].split()
    list_kShingles.append([shingle for shingle in ngrams(tokens, k)])
    list_hashed.append([hash(shingle) for shingle in ngrams(tokens, k)])

In [110]:
jac_sim = pd.DataFrame(columns=['Doc1', 'Doc2', 'Jaccard_Score'])
for i in range(nrow):
    for j in range(nrow):
        if i != j:
            jac_sim = jac_sim.append({'Doc1': 'Doc'+str(i), 'Doc2': 'Doc'+str(j), 'Jaccard_Score': jaccard_similarity(list_hashed[i], list_hashed[j])}, ignore_index=True)

In [111]:
jac_sim

       Doc1   Doc2  Jaccard_Score
0      Doc0   Doc1       0.000000
1      Doc0   Doc2       0.000000
2      Doc0   Doc3       0.000000
3      Doc0   Doc4       0.002688
4      Doc0   Doc5       0.003135
...     ...    ...            ...
9895  Doc99  Doc94       0.000000
9896  Doc99  Doc95       0.000000
9897  Doc99  Doc96       0.000000
9898  Doc99  Doc97       0.000000
9899  Doc99  Doc98       0.000000

[9900 rows x 3 columns]

In [105]:
corpus[17]

'In object-oriented programming, inheritance is a way to form new classes (instances of which are called objects) using classes that have already been defined. The inheritance concept was invented in 1967 for Simula. The new classes, known as derived classes, take over (or inherit) attribute and behaviour of the pre-existing classes, which are referred to as base classes (or ancestor classes). It is intended to help reuse existing code with little or no modification. Inheritance provides the support for representation by categorization in computer languages. Categorization is a powerful mechanism number of information processing, crucial to human learning by means of generalization (what is known about specific entities is applied to a wider group given a belongs relation can be established) and cognitive economy (less information needs to be stored about each specific entity, only its particularities). Inheritance is also sometimes called generalization, because the is-a relationships represent a hierarchy between classes of objects. For instance, a "fruit" is a generalization of "apple", "orange", "mango" and many others. One can consider fruit to be an abstraction of apple, orange, etc. Conversely, since apples are fruit (i.e., an apple is-a fruit), apples may naturally inherit all the properties common to all fruit, such as being a fleshy container for the seed of a plant. An advantage of inheritance is that modules with sufficiently similar interfaces can share a lot of code, reducing the complexity of the program. Inheritance therefore has another view, a dual, called polymorphism, which describes many pieces of code being controlled by shared control code. Inheritance is typically accomplished either by overriding (replacing) one or more methods exposed by ancestor, or by adding new methods to those exposed by an ancestor. '

In [106]:
corpus[35]

'In object-oriented programming, inheritance is a way to form new classes (instances of which are called objects) using classes that have already been defined. The inheritance concept was invented in 1967 for Simula. The new classes, known as derived classes, take over (or inherit) attributes and behavior of the pre-existing classes, which are referred to as base classes (or ancestor classes). It is intended to help reuse existing code with little or no modification. Inheritance provides the support for representation by categorization in computer languages. Categorization is a powerful mechanism number of information processing, crucial to human learning by means of generalization (what is known about specific entities is applied to a wider group given a belongs relation can be established) and cognitive economy (less information needs to be stored about each specific entity, only its particularities). Inheritance is also sometimes called generalization, because the is-a relationships represent a hierarchy between classes of objects. For instance, a "fruit" is a generalization of "apple", "orange", "mango" and many others. One can consider fruit to be an abstraction of apple, orange, etc. Conversely, since apples are fruit (i.e., an apple is-a fruit), apples may naturally inherit all the properties common to all fruit, such as being a fleshy container for the seed of a plant. An advantage of inheritance is that modules with sufficiently similar interfaces can share a lot of code, reducing the complexity of the program. Inheritance therefore has another view, a dual, called polymorphism, which describes many pieces of code being controlled by shared control code. Inheritance is typically accomplished either by overriding (replacing) one or more methods exposed by ancestor, or by adding new methods to those exposed by an ancestor. Complex inheritance, or inheritance used within a design that is not sufficiently mature, may lead to the Yo-yo problem.'

In [107]:
global_hash = list(set(per_hash for per_doc in list_hashed for per_hash in per_doc))

In [108]:
matrix_input = {}
for i in range(len(list_hashed)):
    matrix_input['Doc'+str(i)] = [ 1 if single_hash in list_hashed[i] else 0 for single_hash in global_hash ]

In [133]:
chr_matrix = pd.DataFrame(matrix_input, index=global_hash).reset_index(drop=True)

In [134]:
chr_matrix

,Doc0,Doc1,Doc2,Doc3,Doc4,Doc5,Doc6,Doc7,Doc8,Doc9,...,Doc90,Doc91,Doc92,Doc93,Doc94,Doc95,Doc96,Doc97,Doc98,Doc99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13881,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13882,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13883,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13884,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
13885,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [139]:
signature_num = 4
nrow_matrix = chr_matrix.shape[0]
prime = 13887
np.random.seed(12345)
coeff_a = np.random.choice(nrow_matrix, size=signature_num, replace=False)
coeff_b = np.random.choice(nrow_matrix, size=signature_num, replace=False)

In [140]:
coeff_a

array([ 6176,  2748, 13072, 12584])

In [141]:
coeff_b

array([ 2831, 11313,   600,   279])

In [142]:
matrix_permutation = pd.DataFrame(columns=['Hash'+str(j) for j in range(signature_num)])
for i in range(nrow_matrix):
    dict_hash = {}
    for j in range(signature_num):
        dict_hash['Hash'+str(j)] = ( coeff_a[j] * i + coeff_b[j] ) % prime
    matrix_permutation = matrix_permutation.append(dict_hash, ignore_index=True)

In [143]:
matrix_permutation

       Hash0  Hash1  Hash2  Hash3
0       2831  11313    600    279
1       9007    174  13672  12863
2       1296   2922  12857  11560
3       7472   5670  12042  10257
4      13648   8418  11227   8954
...      ...    ...    ...    ...
13881   7436   8712   5490   8097
13882  13612  11460   4675   6794
13883   5901    321   3860   5491
13884  12077   3069   3045   4188
13885   4366   5817   2230   2885

[13886 rows x 4 columns]

In [183]:
matrix_signature = pd.DataFrame(columns=['Doc'+str(j) for j in range(nrow)])
for i in range(signature_num):
    dict_doc = {}
    idx = list(matrix_permutation[['Hash'+str(i)]].values.ravel())
    for j in range(nrow):
        dict_doc['Doc'+str(j)] = np.where(chr_matrix.reindex(idx)[['Doc'+str(j)]] == 1)[0].min()
    matrix_signature = matrix_signature.append(dict_doc, ignore_index=True)

In [184]:
matrix_signature

,Doc0,Doc1,Doc2,Doc3,Doc4,Doc5,Doc6,Doc7,Doc8,Doc9,...,Doc90,Doc91,Doc92,Doc93,Doc94,Doc95,Doc96,Doc97,Doc98,Doc99
0,71,304,285,29,55,22,150,64,15,93,...,3,30,14,12,23,25,51,31,5,101
1,119,308,278,140,116,97,278,180,5,35,...,12,72,47,3,170,32,48,22,27,80
2,12,427,125,0,140,154,125,50,20,112,...,179,88,39,47,70,255,23,119,155,44
3,18,55,88,15,10,11,88,12,111,66,...,185,16,41,98,36,88,86,94,3,6

In [196]:
matrix_signature.loc[:,'Doc17'].eq(matrix_signature.loc[:,'Doc35']).sum()/signature_num

0.75

In [197]:
sign_sim = pd.DataFrame(columns=['Doc1', 'Doc2', 'Signature_Score'])
for i in range(nrow):
    for j in range(nrow):
        if i != j:
            sign_sim = sign_sim.append({'Doc1': 'Doc'+str(i), 'Doc2': 'Doc'+str(j), 'Signature_Score': matrix_signature.loc[:,'Doc'+str(i)].eq(matrix_signature.loc[:,'Doc'+str(j)]).sum()/signature_num}, ignore_index=True)

In [198]:
sign_sim

       Doc1   Doc2  Signature_Score
0      Doc0   Doc1              0.0
1      Doc0   Doc2              0.0
2      Doc0   Doc3              0.0
3      Doc0   Doc4              0.0
4      Doc0   Doc5              0.0
...     ...    ...              ...
9895  Doc99  Doc94              0.0
9896  Doc99  Doc95              0.0
9897  Doc99  Doc96              0.0
9898  Doc99  Doc97              0.0
9899  Doc99  Doc98              0.0

[9900 rows x 3 columns]

In [203]:
pd.merge(jac_sim, sign_sim, on=['Doc1','Doc2']).sort_values(by='Signature_Score', ascending=False)

       Doc1   Doc2  Jaccard_Score  Signature_Score
3517  Doc35  Doc53       0.886364             1.00
5705  Doc57  Doc63       0.446575             1.00
5282  Doc53  Doc35       0.886364             1.00
6294  Doc63  Doc57       0.446575             1.00
3497  Doc35  Doc32       0.381107             0.75
...     ...    ...            ...              ...
3320  Doc33  Doc54       0.000000             0.00
3321  Doc33  Doc55       0.001742             0.00
3322  Doc33  Doc56       0.003384             0.00
3324  Doc33  Doc58       0.000000             0.00
9899  Doc99  Doc98       0.000000             0.00

[9900 rows x 4 columns]